name: Deploy to GitHub Pages


on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /GitHubPagesNextjs

    strategy:
      matrix:
        node-version: [14.x]


    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        working-directory: 'docs'
        run: npm ci
      - name: Build project        
        working-directory: 'docs'
        run: npm run build
      - name: Export static files
        working-directory: 'docs'
        run: npm run export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out
